#!/usr/bin/env bash

set -e

if [ ! -z ${PLUGIN_KUBE_CONFIG} ]; then
  echo ${PLUGIN_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
else
  echo "ERROR: no configuration has been provided"
fi

/usr/local/bin/kubectl version

/usr/local/bin/kubectl cluster-info
