#!/usr/bin/env bash

set -e

PATH="/opt/kubectl/bin/:$PATH"

INIT_FILE=/opt/kubectl/initialized

if [ ! -f ${INIT_FILE} ]; then
    /opt/kubectl/bin/init-kubectl > ${INIT_FILE}
    touch ${INIT_FILE}
fi

/usr/local/bin/kubectl $@
