#!/usr/bin/env bash

set -e

PATH="/opt/bitnami/kubectl/bin:$PATH"

INIT_FILE=/opt/kubectl/initialized

if [ ! -f ${INIT_FILE} ]; then
    init-kubectl > /dev/null
    touch ${INIT_FILE}
fi

kubectl $@
